spring:
    datasource:
        url: jdbc:mysql://localhost:3306/taxi_db?useSSL=false
        username: root
        password: Hanuman123@
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL8Dialect
server:
    servlet:
        context-path: /api